FROM php:8.2-apache
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo pdo_mysql
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests
RUN a2enmod rewrite

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install system dependencies
RUN apt-get update && apt-get install -y \
  git \
  curl \
  #libpng-dev \
  #libonig-dev \
  #libxml2-dev \
  zip \
  unzip \
  npm
