FROM php:7.1-apache
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo pdo_mysql
#RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests
RUN a2enmod rewrite
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install system dependencies
#RUN apt-get update && apt-get install -y \
  #  git \  1
   # curl \
  #  libpng-dev \
   # libonig-dev \
  #  libxml2-dev \
   # zip \
   # unzip

# Create system user to run Composer and Artisan Commands
#RUN useradd -G www-data,root -u $uid -d /home/$user $user
#RUN mkdir -p /home/$user/.composer && \
   # chown -R $user:$user /home/$user

#USER $user