version: '3.8'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      #- ./config/nginx/vhost/:/etc/nginx/conf.d/
      - ./config/nginx/vhost/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php56
      - php71
      - php74
      - php82
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  php56:
    build:
      context: .
      dockerfile: Dockerfile.56
    ports:
      - '56:80'
    volumes:
      - ./sites:/var/www/html/
      - ./config/vhosts:/etc/apache2/sites-enabled/
      - ./config/vhosts:/etc/apache2/sites-available/
      #- ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      #- ./config/apache2/ports.conf:/etc/apache2/ports.conf
  php82:
    build:
      context: .
      dockerfile: Dockerfile.82
    ports:
      - '82:80'
    volumes:
      - ./sites:/var/www/html/
      - ./config/vhosts:/etc/apache2/sites-enabled/
      - ./config/vhosts:/etc/apache2/sites-available/
      #- ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      #- ./config/apache2/ports.conf:/etc/apache2/ports.conf
  php74:
    build:
      context: .
      dockerfile: Dockerfile.74
    ports:
      - '74:80'
    volumes:
      - ./sites:/var/www/html/
      - ./config/vhosts:/etc/apache2/sites-enabled/
      - ./config/vhosts:/etc/apache2/sites-available/
      #- ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      #- ./config/apache2/ports.conf:/etc/apache2/ports.conf
  php71:
    build:
      context: .
      dockerfile: Dockerfile.71
    ports:
      - '71:80'
    volumes:
      - ./sites:/var/www/html/
      - ./config/vhosts:/etc/apache2/sites-enabled/
      - ./config/vhosts:/etc/apache2/sites-available/
      #- ./config/apache2/apache2.conf:/etc/apache2/apache2.conf
      #- ./config/apache2/ports.conf:/etc/apache2/ports.conf

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password #example of a password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80